#pragma once
// The rules engine. Knows nothing about concrete cards; all card behaviour is
// delegated to EffectHost (Lua). See effect_host.hpp.
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <utility>
#include <vector>

#include "engine/card_names.hpp"
#include "core/state.hpp"
#include "core/types.hpp"
#include "protocol/agent.hpp"

namespace fy {

struct Config {
  int turnLimit = 40;         // 40 turns without a finish -> draw
  int perTurnSeconds = 180;   // 每回合 3min
  int reserveSeconds = 360;   // 留存 6min (not refilled)
  int illegalTolerance = 1;   // how many illegal moves before forfeit
  bool enforceTime = false;
  // Card-effect Lua errors abort the match instead of silently doing nothing.
  bool strictLua = true;
  uint64_t seed = 0;
  // "hajimari" = fixed tutorial decks; "standard" = 三拾一舍 draft + build.
  std::string mode = "hajimari";
  std::string p0Set = "hajimari.ukiro";
  std::string p1Set = "hajimari.okika";
  // Deck-sets available for the draft (Phase 2: the four O decks).
  std::vector<std::string> draftPool = {"yurina", "saine", "himika", "tokoyo", "oboro",
                                        "yukihi", "shinra", "hagane", "chikage", "kururu",
                                        "thallya", "raira"};
};

// A live attack instance (virtual attacks included).
struct Attack {
  Player attacker = P0;
  int sourceInst = -1;        // card that generated it, -1 if purely virtual
  bool fromSpecial = false;   // generated by a 切札
  bool fromResponse = false;  // this attack IS a response card's attack -> cannot be responded to
  Range range;
  std::optional<int> aura, life;
  int auraDelta = 0, lifeDelta = 0;
  uint32_t keywords = 0;
  bool negateDamage = false;       // 驳论: negate damage but keep附加效果
  bool terminal = false;           // dynamic 终端 (电磁炮 黄)
  bool counted = false;            // already counted toward 每回合攻击次数
  bool attackerChoosesDamage = false;  // 畏掠
  bool negated = false;       // 打消
  bool missed = false;        // range re-check failed
  bool hit = false;
};

class EffectHost;

class Engine {
 public:
  explicit Engine(Config cfg = {});
  ~Engine();

  Config cfg;
  GameState st;
  std::vector<CardDef> defs;

  void load_content(const std::string& luaFile);
  void set_agent(Player p, Agent* a);

  // ---- accessors -----------------------------------------------------------
  PlayerState& ps(Player p) { return st.p[p]; }
  const PlayerState& ps(Player p) const { return st.p[p]; }
  CardInstance& ci(int inst) { return st.insts[static_cast<size_t>(inst)]; }
  const CardInstance& ci(int inst) const { return st.insts[static_cast<size_t>(inst)]; }
  const CardDef& def_of(int inst) const { return defs[static_cast<size_t>(ci(inst).def)]; }
  const CardDef& def(int defId) const { return defs[static_cast<size_t>(defId)]; }

  nlohmann::json observation(Player viewer) const;

  Decision decide(Player p, Request req);

  // ---- decision validation -------------------------------------------------
  // Agents are untrusted: every decision is validated before use. Illegal
  // indices are dropped, disabled or duplicate picks are refused, and the
  // selection is repaired to [minSel, maxSel]. Violations are counted per
  // player; past cfg.illegalTolerance the offender forfeits the match.
  int illegal_count(Player p) const { return illegalCount_[p]; }
  int lua_error_count() const;  // card-effect runtime errors during the match
  bool forfeited() const { return forfeited_; }

  // ---- match flow ----------------------------------------------------------
  void setup_match();
  void run();

  // ---- replay / determinism ------------------------------------------------
  // The engine records every decision it receives. Replaying the same seed and
  // journal reproduces the match exactly; state_hash() lets us verify it.
  void start_recording();
  void load_journal(const nlohmann::json& j);
  nlohmann::json journal_json() const;
  uint64_t state_hash() const;
  bool replaying() const { return replaying_; }

  // ---- primitives (used by the engine and by Lua) --------------------------
  int add_instance(int defId, Player owner);
  void move_card(int inst, Zone z);
  void move_card_top(int inst);      // put on top of owner's deck (next draw)
  void move_card_bottom(int inst);   // put on the bottom of owner's deck
  int amount(AreaRef a) const;
  void add_crystals(AreaRef a, int n);
  // cardEffect==false for basic actions (迷烟 only negates card effects).
  int move_crystals(AreaRef from, AreaRef to, int n, bool cardEffect = true);

  void draw(Player p, int n);
  void gain_vigor(Player p, int n);
  void give_cower(Player p);
  void lose_life(Player p, int n, bool triggerBreak = true);
  void damage_life(Player target, int n, AreaKind to, bool triggerBreak);
  void deal_damage(Player target, std::optional<int> aura, std::optional<int> life,
                   uint32_t keywords = 0);
  void rebuild(Player p, bool costLife);
  void resolve_attack(Attack& a);
  // Registers an attack with the per-turn counters and fires `attack_declared`.
  // Idempotent for a given Attack, so declare-then-resolve counts it exactly once.
  void declare_attack(Attack& a);
  void play_card(Player p, int inst, bool asResponse, bool zenkai = false);
  void consume_enhance_crystal(int inst);
  void check_win();

  // ---- extended mechanics --------------------------------------------------
  int effective_armor(Player p) const;   // 实装 + “视作装”的卡上结晶
  void spend_aura(Player target, int n);  // consume “视作装”结晶 first, then real aura
  int cut_cost(Player p, int defId, int inst);       // dynamic 切札 费用
  int max_aura(Player p) const;                      // 装上限（徒寄之八重樱 -> 8）
  int effective_hand_limit(Player p) const;          // 盖伏保留上限
  bool playable_card(Player p, int inst);            // playable-in-main predicate (e.g. 决死限定)
  bool respondable_card(Player p, int inst);         // response capability (含识破/终焉)
  bool basic_legal(Player p, BasicAction a) const;
  bool do_basic(Player p, BasicAction a);            // free basic action (no vigor/cover)
  void free_basics(Player p, int maxTimes);
  void free_basics_of(Player p, int maxTimes, const std::vector<std::string>& allowed);
  Attack make_attack(Player p, int inst, bool asResponse, bool consumePending);
  bool any_lock_distance() const;
  void reveal_hand(Player p);

  // ---- Phase 3 extensions --------------------------------------------------
  int used_special_count(Player p, const std::string& goddess) const;  // 正面向上切札数
  bool card_has_goddess(int inst, const std::string& g) const;
  void reset_special(int inst);       // 神座渡: set a used 切札 back to unused
  void clamp_aura(Player p);          // if max aura dropped, move excess (自装) to 虚
  void die(Player p);                 // 炎天: self loss
  void end_current_main();            // 绝唱绝华: end the opponent's main phase
  bool main_aborted() const { return abortMain_; }
  int last_damage_side() const { return lastDmgSide_; }      // 0 none, 1 aura, 2 life
  int last_damage_amount() const { return lastDmgAmount_; }
  bool last_damage_from_attack() const { return lastDmgFromAttack_; }
  void store_int(int inst, const std::string& key, int v);   // per-card scratch (神座渡 X)
  int load_int(int inst, const std::string& key, int def = 0) const;
  std::vector<std::string> available_forms(const std::string& goddess) const;
  std::vector<int> deck_def_ids(const std::string& goddess, const std::string& form) const;

  // ---- Oboro: parts / cover play / electronic setup / EX ------------------
  int assembled_count(Player p) const;
  int cover_count(Player p) const { return static_cast<int>(ps(p).cover.size()); }
  std::vector<int> unassembled_parts(Player p) const;
  std::vector<int> assembled_parts(Player p) const;
  void set_assembled(int inst, bool v);
  void assemble_part(Player p, int inst);   // enforces the hard cap of 5
  void disassemble_part(Player p, int inst);
  int part_by_def(Player p, int def) const;
  bool has_named_active(Player p, const std::string& name) const;
  bool has_oboro_parts(Player p) const { return !ps(p).parts.empty(); }
  bool current_from_cover() const;
  void play_from_cover(Player p, int inst, bool asResponse, bool toDeckAfter);
  void do_electronic_setup(Player p);
  int gain_extra(Player p, const std::string& name);  // 神代枝: EX -> special zone
  bool try_revive(Player p);                          // 最后的结晶 death window
  int assemble_one(Player p);                         // choose an unassembled part to assemble
  void disassemble_to(Player p, int maxCount);
  void assemble_many(Player p, int x);
  void remove_card(int inst);                         // move out of the game

  // ---- Raira: 风雷 / 岚之力 -------------------------------------------------
  bool raira_can(Player p, const std::string& kind, int tier) const;
  bool raira_spend(Player p, const std::string& kind, int tier);
  void raira_gain_restrict(Player p) { ps(p).rairaGainRestricted = true; }
  void raira_perm_cut(Player p) { ps(p).cutCostPermanent = true; }
  void cover_card(int inst);                          // move a card into its cover pile (face down)
  void cover_deck(Player p);                          // 紧那罗: cover the whole deck
  std::string card_zone(int inst) const;
  void use_from_cover(int inst, bool asResponse);     // 分身/鸢影: use a cover card
  void force_unrespondable() { forceUnrespondable_ = true; }
  bool aura_damaged_this_turn(Player p) const { return auraDamagedThisTurn_[p]; }
  void gain_external(AreaRef a, int n);   // 神代枝: crystal added from outside the game
  int external_added() const { return externalAdded_; }
  void init_parts(Player p);              // give Oboro A2 its parts pool
  void init_bag(Player p);                // give Chikage its 毒袋

  // ---- Yukihi: 变貌 (weapon 伞/簪) -----------------------------------------
  bool umbrella(Player p) const { return ps(p).umbrella; }
  void switch_weapon(Player p, int source = -1);
  bool shared_range(Player p) const { return has_named_active(p, "无常其心"); }
  int enhance_crystal_total(Player p) const;
  int cards_played_this_turn(Player p) const { return ps(p).cardsPlayedThisTurn; }
  int dust_to_card(int inst, int n);
  void set_used(int inst);  // mark a 切札 used without paying (神涉装置)
  void use_card(int inst, bool asResponse);  // use a card from discard/cover

  // ---- Shinra: 策略 / 封印 / 借用对手的牌 ---------------------------------
  int strategy(Player p) const { return ps(p).strategy; }
  void prepare_strategy(Player p);
  void seal_card(int host, int card);
  void return_sealed(int host);
  void use_foreign_card(Player user, int inst);  // resolve another player's card
  void discard_top(Player p);
  void cover_top(Player p);
  bool is_normal_card(int inst) const { return def_of(inst).kind == CardKind::Normal; }
  bool is_enhance(int inst) const { return def_of(inst).type == CardType::Enhance; }
  // True while a card's "展开中" text applies: a normal 付与 in the enhance zone,
  // or a 切札付与 that is used and still holds at least one 献. A 付与 with no
  // crystals left is no longer expanded (even though a 切札 stays in the special
  // zone in its "used" state).
  bool enhance_active(int inst) const;
  std::vector<int> enhances(Player p) const;  // all active 付与, incl. 切札付与
  void reuse_special(int inst);              // 诸式理解: resolve a used cut in place
  int drain_card_crystals(int inst, int n);  // move up to n crystals from a card to 虚

  // ---- Hagane: 离心 / 全开 / 炼成 ------------------------------------------
  int distance_at_turn_start() const { return distanceAtTurnStart_; }
  bool attacked_this_turn(Player p) const { return attackedThisTurn_[p]; }
  bool played_centrifugal_this_turn(Player p) const { return playedCentrifugalThisTurn_[p]; }
  bool played_liancheng_this_turn(Player p) const { return playedLianchengThisTurn_[p]; }
  bool used_this_turn(int inst) const { return ci(inst).usedThisTurn; }
  bool zenkai_active() const { return zenkaiActive_; }
  bool centrifugal_ok(Player p) const {
    // 离心 compares the *effective* distance (README ruling 80: 持续修正计入).
    return distance() >= distanceAtTurnStart_ + 2 && !attackedThisTurn_[p];
  }
  // 二重奏·弹奏冰瞑: "本回合内你不能攻击" — blocks every attack, generated included.
  bool can_attack(Player p) const { return !ps(p).cannotAttack; }
  // 迟缓毒: "你不能使用攻击牌" — forbids playing attack *cards* (including as a
  // response), but not attacks generated by card effects.
  bool attack_card_forbidden(Player p) const {
    return has_named_active(p, cards::kChikanDoku);
  }
  std::vector<int> special_cards(Player p) const { return ps(p).special; }
  bool is_used(int inst) const { return ci(inst).faceUp; }
  bool is_my_turn(Player p) const { return st.active == p; }
  void random_discard(Player p);
  void discard_deck(Player p);
  int find_named(Player p, const std::string& name) const;
  int count_named(Player p, const std::string& name) const;  // instances the player holds
  int sealed_card(int host) const;

  // ---- Chikage: 毒袋 / 毒 / 持续距离 ----------------------------------------
  int distance() const;          // effective distance (raw + active distanceMods, clamped >=0)
  int distance_delta() const;
  // 达人距离 (近身距离): shared threshold, default 2, modified by active cards.
  int near_distance() const;
  bool is_poison(int inst) const { return def_of(inst).isPoison; }
  std::vector<int> poison_bag(Player p) const { return ps(p).bag; }
  void place_poison(int inst, Player holder, Zone z);
  void return_poison(int inst);
  void force_move(int inst, Zone z);   // bypass the poison discard/cover protection
  void float_poisons(Player p);        // move poisons in p's deck to the top
  void set_cannot_advance(Player p) { ps(p).cannotAdvance = true; }
  bool did_basic_this_turn(Player p) const { return didBasicThisTurn_[p]; }

  // ---- Kururu: 机巧 (color combinations among face-up cards) --------------
  uint32_t card_colors(int inst) const;
  std::string card_colors_str(int inst) const;
  bool keisou(Player p, const std::string& combo, bool otherOnly = false) const;
  int keisou_amount(Player p, int base);  // 骇客装置: double one 机巧 slot's numbers
  void reveal_opponent_specials(Player p) { revealOppSpecials_[p] = true; }
  void play_hand_card(Player p, int inst) { play_card(p, inst, false); }
  std::vector<std::string> goddess_normal_names(Player p) const;
  bool guess_name(Player guesser, int cardInst);  // 最终搜寻
  bool rebuilt_this_turn(Player p) const { return rebuiltThisTurn_[p]; }
  bool used_fullpower_this_turn(Player p) const { return usedFullPowerThisTurn_[p]; }
  void set_pending_nagi_adjust(int n) { pendingNagiAdjust_ = n; }
  int note_attack(Player p) { return ++attacksThisTurn_[p]; }
  int attacks_this_turn(Player p) const { return attacksThisTurn_[p]; }
  void add_unused_cuts(Player p);  // 最终搜寻: unused (Removed) cuts -> special zone, unused
  int rng_below(int n) { return st.rng.below(n); }

  // ---- Thallya: 蒸汽 / 气动 / 变形 ------------------------------------------
  void burn(Player p, int x);
  void recover(Player p, int x);
  void pneumatic(Player p);
  void transform(Player p, const std::string& name);
  void reset_steam_at_turn_start(Player p);  // 气动 lasts until the owner's next turn
  std::vector<int> active_transform_defs(Player p) const;
  bool can_burn(Player p, int x) const;
  bool transform_is(Player p, const std::string& name) const;
  void transform_choose(Player p);
  void init_transforms(Player p, const std::string& form);
  std::vector<int> transform_cards(Player p) const;
  int active_transform_inst(Player p) const;  // instance of the current 变形 aura

  // ---- tracing / replay viewer --------------------------------------------
  struct StackEntry {
    int def = -1;
    Player owner = P0;
    bool fromCover = false;
  };
  void start_trace() {
    tracing_ = true;
    frames_ = nlohmann::json::array();
  }
  nlohmann::json full_state_json() const;  // everything, hidden info included
  nlohmann::json trace_json() const;       // frames + meta + result
  std::string result_text() const;

  // The attack currently being responded to (for ctx:responding_attack()).
  Attack* currentResponding = nullptr;

 private:
  std::unique_ptr<EffectHost> effects_;
  Agent* agents_[2] = {nullptr, nullptr};
  bool mainDirty_ = false;
  bool abortMain_ = false;
  int lastDmgSide_ = 0;      // 0 none, 1 aura, 2 life
  int lastDmgAmount_ = 0;
  bool lastDmgFromAttack_ = false;
  std::vector<std::string> playerSets_[2];
  std::map<std::pair<int, std::string>, int> vars_;
  bool tracing_ = false;
  nlohmann::json frames_ = nlohmann::json::array();
  std::string phase_ = "setup";
  std::vector<StackEntry> callStack_;
  std::vector<std::pair<std::string, std::string>> draftPicks_[2];
  std::pair<std::string, std::string> draftBans_[2];
  bool hasDraft_[2] = {false, false};
  // per-turn event counters (for "first time this turn" triggers)
  int attacksThisTurn_[2] = {0, 0};
  int auraChangesThisTurn_[2] = {0, 0};
  int auraChangeFired_[2] = {0, 0};
  int attackFirstFired_[2] = {0, 0};
  bool auraDamagedThisTurn_[2] = {false, false};
  int normalNonYukihi_[2] = {0, 0};
  int distanceAtTurnStart_ = 0;
  bool attackedThisTurn_[2] = {false, false};
  bool playedCentrifugalThisTurn_[2] = {false, false};
  bool playedLianchengThisTurn_[2] = {false, false};
  bool zenkaiActive_ = false;
  bool poisonForce_ = false;
  bool didBasicThisTurn_[2] = {false, false};
  bool rebuiltThisTurn_[2] = {false, false};
  bool usedFullPowerThisTurn_[2] = {false, false};
  int pendingNagiAdjust_ = 0;
  bool ashuraExtraUsed_[2] = {false, false};
  bool damageToDistance_ = false;
  bool keisouDoubled_ = false;
  bool revealOppSpecials_[2] = {false, false};
  bool forceUnrespondable_ = false;
  int externalAdded_ = 0;

  void fire(const char* event, Player subject, Attack* atk = nullptr, int card = -1,
            bool first = false);
  void notify_aura_changed(Player p);

  // Untrusted-decision handling (see decide()).
  Decision sanitize_decision(Player p, const Request& req, Decision d);
  void count_illegal(Player p, const std::string& why);

  int illegalCount_[2] = {0, 0};
  bool forfeited_ = false;

  struct JournalEntry {
    Player player;
    std::string kind;
    std::vector<int> indices;
  };
  bool recording_ = false;
  bool replaying_ = false;
  std::vector<JournalEntry> journal_;
  size_t replay_pos_ = 0;

  // A "pick" is a (goddess, form) pair; form is "O" / "A1" / "A2".
  void setup_player(Player p, const std::vector<std::pair<std::string, std::string>>& picks);
  std::vector<std::pair<std::string, std::string>> draft_pick(Player p);
  std::pair<std::string, std::string> draft_ban(
      Player p, const std::vector<std::pair<std::string, std::string>>& opp);
  void setup_player_sets(Player p, const std::vector<std::string>& sets);
  void build_from_pool(Player p, std::vector<int>& normals, std::vector<int>& specials);
  void run_rebuild(Player p);   // normal rebuild / electronic setup decision
  void resolve_card_effect(Player p, int inst, bool asResponse, bool zenkai = false);
  void play_turn(Player p);
  void start_phase(Player p);
  void main_phase(Player p);
  void cover_phase(Player p);
  void end_phase(Player p);

  void apply_life_damage(Player target, int n, bool triggerBreak);
  void on_life_loss(Player p, int amount, bool triggerBreak);
  // A 付与 that has just lost its last 献 leaves play (and runs 弃置时).
  void drop_enhance_if_empty(int inst);
  void break_enhances(Player p);
  void apply_damage_to(Player target, std::optional<int> aura, std::optional<int> life,
                       uint32_t keywords, int sourceInst, int chooser = -1,
                       bool fromAttack = false);
  bool ask_yes_no(Player p, const std::string& prompt);
  int ask_one(Player p, Request req);
};

}  // namespace fy
